### ISSUE TITLE
Use @Binds when providing an implementation in a module

### ISSUE THREAD

**Issue by jbiral** [kikin81/android_giant_bomb_player#5]
Prefer using `@Binds` when mapping an implementation to its interface (see for extra context: https://dagger.dev/dev-guide/faq.html#why-is-binds-different-from-provides)

For example:
```kt
    @Provides
    @Singleton
    fun provideVideoHelper(videoHelper: VideoApiHelperImpl): VideoApiHelper =
        videoHelper
```

Would be preferred as:
```kt
    @Binds
    abstract fun provideVideoHelper(videoHelper: VideoApiHelperImpl): VideoApiHelper
```

Additionally, prefer having the `@Provides` methods part of a `companion object`, it's more efficient to do so (because Dagger won't create a new class to simply host the provider method.

**Comment by kikin81** [comment]
https://github.com/kikin81/android_giant_bomb_player/pull/18
